@extends('layouts.app')
@section('content')
<div class="page-head"><div><span class="eyebrow">Workspace</span><h1>Dashboard</h1><p>Manage your gig marketing projects and SEO growth from one place.</p></div><div style="display:flex;gap:10px;align-items:center"><div class="card" style="padding:9px 14px"><span class="muted">AI Credits</span> <strong>{{ Auth::user()->ai_credits }}</strong></div><a class="btn" href="{{ route('projects.create') }}">+ New Project</a></div></div>
<div class="grid" style="margin-bottom:18px"><div class="stat"><div class="stat-icon">✦</div><div class="stat-label">AI Credits</div><div class="stat-value">{{ number_format(Auth::user()->ai_credits) }}</div></div><div class="stat"><div class="stat-icon">◫</div><div class="stat-label">Projects</div><div class="stat-value">{{ $projects->count() }}</div></div><div class="stat"><div class="stat-icon">▤</div><div class="stat-label">SEO Pages</div><div class="stat-value">{{ number_format($projects->sum('pages_count')) }}</div></div><div class="stat"><div class="stat-icon">↗</div><div class="stat-label">Plan</div><div class="stat-value" style="font-size:22px;text-transform:capitalize">{{ Auth::user()->plan ?: 'Free' }}</div></div></div>
@if($errors->any())<div class="alert error"><strong>Something needs attention</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
@if($hostedSiteLinks->isNotEmpty())
<div class="card" style="margin-bottom:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px"><div><h2 style="margin:0">Free HTML Sites</h2><p class="muted" style="margin:4px 0 0">Ready-to-use hosted sites and setup resources provided by GigRanker.</p></div><span class="badge">{{ $hostedSiteLinks->count() }} Available</span></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px">
@foreach($hostedSiteLinks as $link)<div style="border:1px solid #eaecf0;border-radius:12px;padding:18px;background:#fff"><div style="display:flex;justify-content:space-between;gap:10px"><div><strong>{{ $link->name }}</strong><p class="muted" style="font-size:12px;line-height:1.5;margin:6px 0 14px">{{ $link->description ?: 'Free HTML website resource.' }}</p></div><span class="badge">HTML</span></div><div style="display:grid;gap:8px"><a class="btn" href="{{ $link->site_link }}" target="_blank" rel="noopener">Open Site</a>@if($link->setup_link)<a class="btn secondary" href="{{ $link->setup_link }}" target="_blank" rel="noopener">Setup Link</a>@endif</div></div>@endforeach
</div></div>
@endif
<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:18px"><div><h2 style="margin:0">Your Projects</h2><p class="muted" style="margin:4px 0 0">Build, generate and preview your SEO websites.</p></div><a class="btn secondary" href="{{ route('projects.create') }}">New Project</a></div>
@if($projects->isEmpty())<div style="text-align:center;padding:48px 15px;border:1px dashed #d0d5dd;border-radius:10px"><div class="stat-icon" style="float:none;margin:0 auto 14px">＋</div><h2>Create your first project</h2><p class="muted">Add your freelance gig information and generate SEO-ready pages from your workspace.</p><a class="btn" href="{{ route('projects.create') }}">Create First Project</a></div>
@else<div style="overflow:auto"><table><thead><tr><th>Project</th><th>Gig</th><th>Target</th><th>Pages</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach($projects as $project)<tr><td><strong>{{ $project->name }}</strong><br><span class="muted">{{ $project->site_url ?: 'No site URL' }}</span></td><td><a style="color:#465fff" href="{{ $project->gig_url }}" target="_blank" rel="noopener">{{ $project->gig_title ?: 'View gig' }}</a></td><td>{{ $project->target_country ?: '—' }}{{ $project->target_city ? ', '.$project->target_city : '' }}</td><td><strong>{{ $project->pages_count }}</strong></td><td><span class="badge">{{ ucfirst($project->status) }}</span></td><td><div style="display:flex;gap:7px;flex-wrap:wrap"><form method="POST" action="{{ route('projects.generate', $project) }}">@csrf<input type="hidden" name="page_count" value="10"><button class="btn secondary" type="submit" {{ in_array($project->status,['generating'],true)||Auth::user()->ai_credits<10?'disabled':'' }}>Generate</button></form>@if($project->pages_count>0)<a class="btn secondary" href="{{ route('projects.preview',$project) }}">Preview</a><a class="btn secondary" href="{{ route('projects.export',$project) }}">ZIP</a>@endif</div></td></tr>@endforeach</tbody></table></div><p class="muted" style="font-size:12px;margin:15px 0 0">Generation costs 1 AI credit per requested SEO page. Failed generations are refunded.</p>@endif</div>
@endsection
