@extends('layouts.app')
@section('content')
<div style="max-width:1120px;margin:auto"><span class="badge">Admin • AI Control Center</span><h1>AI Provider Manager</h1><p class="muted">Configure server-side AI, routing, provider pricing and credit controls.</p>
@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><strong>Free AI:</strong> OpenRouter can route to currently available free models; Groq may offer free/developer access subject to current limits. Add your own keys—never hard-code shared keys.</div>
<form method="POST" action="{{ route('admin.ai.update') }}">@csrf
<div class="card" style="margin-top:18px"><h2>⚡ Global Routing</h2><div class="grid"><label>Primary provider<select name="primary">@foreach(['openrouter'=>'OpenRouter • Free Models','groq'=>'Groq','openai'=>'OpenAI','anthropic'=>'Claude / Anthropic','gemini'=>'Google Gemini','custom'=>'Custom OpenAI-compatible'] as $value=>$label)<option value="{{ $value }}" @selected($primary===$value)>{{ $label }}</option>@endforeach</select></label><label>Fallback chain<input name="fallbacks" value="{{ $fallbacks }}" placeholder="groq,openrouter,gemini"></label></div><p class="muted">Example: OpenRouter → Groq → Gemini.</p></div>
@foreach($providers as $name=>$p)
@php($labels=['openai'=>'OpenAI','anthropic'=>'Claude / Anthropic','gemini'=>'Google Gemini','openrouter'=>'OpenRouter • Free Models','groq'=>'Groq • Free/Developer','custom'=>'Custom OpenAI-Compatible']) @php($defaults=['openrouter'=>'https://openrouter.ai/api/v1','groq'=>'https://api.groq.com/openai/v1'])
<div class="card" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h2 style="margin:0">{{ $labels[$name] }}</h2><span class="badge">{{ $p['api_key_set']?'Configured':'Not configured' }}</span></div><div class="grid" style="margin-top:15px"><label>API Key<input type="password" name="{{ $name }}_api_key" placeholder="{{ $p['api_key_set']?'Saved — leave blank to keep':'Enter your own API key' }}" autocomplete="new-password"></label><label>Model<input name="{{ $name }}_model" value="{{ $p['model'] }}" placeholder="{{ $name==='openrouter'?'openrouter/free':($name==='groq'?'llama-3.3-70b-versatile':'Provider model') }}"></label><label style="grid-column:1/-1">Base URL<input type="url" name="{{ $name }}_base_url" value="{{ $p['base_url']?:($defaults[$name]??'') }}" placeholder="https://api.example.com/v1"></label><label>Input price / 1M tokens (USD)<input type="number" step="0.000001" min="0" name="{{ $name }}_input_price" value="{{ $p['input_price'] }}" placeholder="0"></label><label>Output price / 1M tokens (USD)<input type="number" step="0.000001" min="0" name="{{ $name }}_output_price" value="{{ $p['output_price'] }}" placeholder="0"></label></div><label style="display:block;margin:12px 0"><input type="checkbox" name="{{ $name }}_enabled" value="1" @checked($p['enabled'])> Enable this provider</label><button class="btn secondary" type="submit" formaction="{{ route('admin.ai.test') }}" formmethod="POST" name="provider" value="{{ $name }}">Test Connection</button></div>
@endforeach
<div class="card" style="margin-top:18px"><h2>📊 Credit & Cost Accounting</h2><p class="muted">SEO generation reserves one credit per requested page. Failed generations refund reserved credits. Cost is an estimate from the token-rate fields above; provider invoices remain authoritative.</p><ul><li>User credits are checked atomically before generation.</li><li>Usage is logged by provider, model, user, credits and estimated cost.</li><li>Admin dashboard shows total requests, credits and estimated spend.</li></ul></div>
<button class="btn" type="submit" style="margin-top:18px">Save All AI Settings</button></form></div>
@endsection
