@extends('layouts.app')
@section('content')
<div style="display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap;margin-bottom:24px"><div><span class="badge">Admin Console</span><h1 style="font-size:38px;line-height:1.1;margin:10px 0 6px">GigRanker Control Center</h1><p class="muted" style="margin:0">Users, payments, AI credits, provider usage and estimated AI cost.</p></div><div style="display:flex;gap:10px"><a class="btn secondary" href="{{ route('admin.ai') }}">AI Providers</a><a class="btn" href="{{ route('admin.payments') }}">Review Payments</a></div></div>
<div class="grid" style="margin-bottom:24px">
@foreach([['Users',$users],['Projects',$projects],['Active subscriptions',$activeSubscriptions],['Pending payments',$pendingPayments],['AI credits remaining',$aiCreditsRemaining],['AI requests',$aiRequests],['AI credits used',$aiCreditsUsed],['Estimated AI cost','$'.number_format($aiEstimatedCost,6)]] as $stat)<div class="card"><div class="muted">{{ $stat[0] }}</div><div style="font-size:30px;font-weight:900;margin-top:6px">{{ is_numeric($stat[1]) ? number_format($stat[1]) : $stat[1] }}</div></div>@endforeach
</div>
<div class="grid" style="align-items:start;margin-bottom:24px"><div class="card"><h2 style="margin-top:0">AI provider usage</h2><table><thead><tr><th>Provider</th><th>Requests</th><th>Credits</th><th>Est. cost</th></tr></thead><tbody>@forelse($aiProviderUsage as $row)<tr><td>{{ $row->provider }}</td><td>{{ number_format($row->requests) }}</td><td>{{ number_format($row->credits) }}</td><td>${{ number_format((float)$row->cost,6) }}</td></tr>@empty<tr><td colspan="4" class="muted">No AI usage yet.</td></tr>@endforelse</tbody></table></div><div class="card"><h2 style="margin-top:0">AI billing controls</h2><p class="muted">Credits are reserved before generation and refunded when generation fails. Costs shown here are estimates based on configured provider rates; provider invoices remain authoritative.</p><a class="btn" href="{{ route('admin.ai') }}">Manage AI</a></div></div>
<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:14px"><div><h2 style="margin:0">Recent payments</h2><p class="muted" style="margin:4px 0">{{ number_format($verifiedPayments) }} verified payments total.</p></div><a href="{{ route('admin.payments') }}">View all</a></div><div style="overflow:auto"><table><thead><tr><th>User</th><th>Plan</th><th>Method</th><th>Amount</th><th>Status</th></tr></thead><tbody>@forelse($recentPayments as $payment)<tr><td>{{ $payment->user->email }}</td><td>{{ ucfirst($payment->plan) }}</td><td>{{ strtoupper($payment->method) }}</td><td>{{ $payment->currency }} {{ number_format((float)$payment->amount,2) }}</td><td><span class="badge">{{ $payment->status }}</span></td></tr>@empty<tr><td colspan="5" class="muted">No payments yet.</td></tr>@endforelse</tbody></table></div></div>
@endsection
