@extends('layouts.app')
@section('content')
<div class="card"><span class="badge">Admin • Deployment</span><h1>GitHub → cPanel Update Center</h1><p class="muted">Check GitHub for a new commit, review it, then explicitly approve deployment.</p>
@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
@if(session('update'))<div class="card" style="margin:18px 0"><h2>New GitHub update detected</h2><p><strong>Commit:</strong> <code>{{ session('update')['sha'] }}</code></p><p>{{ session('update')['message'] }}</p>@if(session('update')['url'])<p><a href="{{ session('update')['url'] }}" target="_blank" rel="noopener">Review on GitHub →</a></p>@endif<form method="POST" action="{{ route('admin.deployment.approve') }}">@csrf<button class="btn" type="submit" onclick="return confirm('Deploy the approved GitHub branch to production?')">Approve & Deploy</button></form></div>@endif
<form method="POST" action="{{ route('admin.deployment.save') }}">@csrf
<div class="grid"><label>cPanel Host / IP<input name="host" value="{{ $host }}" required></label><label>cPanel API Port<input name="port" value="{{ $port }}" readonly></label><label>cPanel Username<input name="user" value="{{ $user }}" required></label><label>cPanel Password / API Token<input type="password" name="secret" placeholder="{{ $secret_set ? 'Saved — leave blank to keep' : 'Enter credential' }}" autocomplete="new-password"></label><label>Repository Root<input name="repository_root" value="{{ $repository_root }}" required></label><label>GitHub Repository<input name="github_repo" value="{{ $github_repo }}" required></label><label>GitHub Branch<input name="github_branch" value="{{ $github_branch }}" required></label><label>GitHub Token (private repo)<input type="password" name="github_token" placeholder="{{ $github_token_set ? 'Saved — leave blank to keep' : 'Optional for public repo' }}" autocomplete="new-password"></label></div><button class="btn" type="submit">Save Connection</button></form>
<div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:18px"><form method="POST" action="{{ route('admin.deployment.test') }}">@csrf<button class="btn secondary">Test cPanel</button></form><form method="POST" action="{{ route('admin.deployment.check') }}">@csrf<button class="btn secondary">Check GitHub Updates</button></form></div>
<p class="muted" style="margin-top:20px">Security: credentials are encrypted in application storage. Prefer a cPanel API token instead of a password. Production deployment remains approval-based.</p></div>
@endsection
