@extends('layouts.admin')
@section('content')
<div class="page-head"><div><h1>Homepage CMS</h1><p>Manage Features, Pricing, FAQ, Testimonials and Footer links without touching code.</p></div><a class="btn secondary" href="{{ route('home') }}" target="_blank">Preview Website ↗</a></div>
<div class="panel" style="margin-bottom:20px"><div class="panel-head"><h2>Add section</h2><span class="badge">CMS</span></div><form method="POST" action="{{ route('admin.homepage.store') }}"><div class="form-grid"><div><label>Type</label><select name="type">@foreach($types as $type)<option value="{{ $type }}">{{ ucwords(str_replace('_',' ', $type)) }}</option>@endforeach</select></div><div><label>Sort order</label><input type="number" name="sort_order" value="0" min="0"></div><div><label>Title</label><input name="title"></div><div><label>Subtitle</label><input name="subtitle"></div><div style="grid-column:1/-1"><label>Description</label><textarea name="description"></textarea></div><div style="grid-column:1/-1"><label>Items JSON</label><textarea name="items_json" placeholder='[{"title":"Fast","description":"Example"}]'></textarea><small class="muted">Use a JSON array. Plans can include price, currency, features and featured fields.</small></div><div><label><input type="checkbox" name="is_active" value="1" checked style="width:auto;margin-right:7px">Active</label></div></div>@csrf<button class="btn" type="submit">Add Section</button></form></div>
@foreach($types as $type)
<div class="panel" style="margin-bottom:20px"><div class="panel-head"><h2>{{ ucwords(str_replace('_',' ', $type)) }}</h2><span class="badge">{{ ($sections[$type] ?? collect())->count() }} sections</span></div>
@if(($sections[$type] ?? collect())->isEmpty())<p class="muted">No {{ $type }} content configured yet.</p>@else
@foreach($sections[$type] as $section)
<div style="border:1px solid #eaecf0;border-radius:10px;padding:16px;margin-bottom:12px"><form method="POST" action="{{ route('admin.homepage.update', $section) }}"><div class="form-grid"><div><label>Title</label><input name="title" value="{{ $section->title }}"></div><div><label>Subtitle</label><input name="subtitle" value="{{ $section->subtitle }}"></div><div><label>Sort order</label><input type="number" name="sort_order" value="{{ $section->sort_order }}"></div><div><label>Active</label><select name="is_active"><option value="1" @selected($section->is_active)>Yes</option><option value="0" @selected(!$section->is_active)>No</option></select></div><div style="grid-column:1/-1"><label>Description</label><textarea name="description">{{ $section->description }}</textarea></div><div style="grid-column:1/-1"><label>Items JSON</label><textarea name="items_json">{{ json_encode($section->items ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</textarea></div></div>@csrf @method('PUT')<div class="actions" style="margin-top:12px"><button class="btn" type="submit">Save</button></div></form><form method="POST" action="{{ route('admin.homepage.destroy', $section) }}" onsubmit="return confirm('Delete this homepage section?')" style="margin-top:8px">@csrf @method('DELETE')<button class="btn danger" type="submit">Delete</button></form></div>
@endforeach
@endif</div>
@endforeach
@endsection
