@extends('layouts.app')
@section('content')
<div style="max-width:980px;margin:auto">
<span class="badge">Admin Settings</span><h1>Payments, Notifications & Email</h1>
<p class="muted">Configure payment and admin notification channels. Secrets are encrypted at rest and never committed to GitHub.</p>
@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admin.settings.update') }}">@csrf
<div class="card"><h2>General & Email</h2><div class="grid">
<label>Site name<input name="site_name" value="{{ old('site_name',$settings['site_name']) }}" required></label><label>Support email<input type="email" name="support_email" value="{{ old('support_email',$settings['support_email']) }}"></label><label>Mail from name<input name="mail_from_name" value="{{ old('mail_from_name',$settings['mail_from_name']) }}" required></label><label>Mail from address<input type="email" name="mail_from_address" value="{{ old('mail_from_address',$settings['mail_from_address']) }}"></label>
</div></div>
<div class="card" style="margin-top:18px"><h2>bKash</h2><p class="muted">Use manual payment by number, or configure official bKash merchant credentials for automatic verification. Never enable auto verification without valid official credentials.</p><label>bKash payment number<input name="bkash_number" value="{{ old('bkash_number',$settings['bkash_number']) }}"></label><div class="grid"><label>App Key<input type="password" name="bkash_app_key" placeholder="{{ $settings['bkash_app_key_set'] ? 'Saved — leave blank to keep it' : 'Optional merchant App Key' }}"></label><label>App Secret<input type="password" name="bkash_app_secret" placeholder="{{ $settings['bkash_app_secret_set'] ? 'Saved — leave blank to keep it' : 'Optional merchant App Secret' }}"></label><label>Username<input name="bkash_username" value="{{ old('bkash_username',$settings['bkash_username']) }}"></label><label>Password<input type="password" name="bkash_password" placeholder="{{ $settings['bkash_password_set'] ? 'Saved — leave blank to keep it' : 'Merchant password' }}"></label><label style="grid-column:1/-1">API Base URL<input name="bkash_base_url" value="{{ old('bkash_base_url',$settings['bkash_base_url']) }}"></label></div><label><input type="checkbox" name="bkash_auto_verify" value="1" @checked($settings['bkash_auto_verify'] === '1')> Enable automatic bKash verification</label></div>
<div class="card" style="margin-top:18px"><h2>BEP20 / USDT</h2><p class="muted">Receiving wallet and official USDT contract. Never enter a private wallet key.</p><div class="grid"><label>Payment address<input name="bep20_payment_address" value="{{ old('bep20_payment_address',$settings['bep20_payment_address']) }}"></label><label>USDT contract<input name="bep20_usdt_contract" value="{{ old('bep20_usdt_contract',$settings['bep20_usdt_contract']) }}"></label><label style="grid-column:1/-1">BSC RPC URL<input name="bep20_rpc_url" value="{{ old('bep20_rpc_url',$settings['bep20_rpc_url']) }}"></label></div></div>
<div class="card" style="margin-top:18px"><h2>Binance Personal Account API</h2><p class="muted">Use a dedicated API key with read-only permissions and IP restrictions where possible. <strong>Do not enable withdrawals.</strong></p><div class="grid"><label>API key<input name="binance_api_key" value="{{ old('binance_api_key',$settings['binance_api_key']) }}" autocomplete="off"></label><label>API secret<input type="password" name="binance_api_secret" placeholder="{{ $settings['binance_api_secret_set'] ? 'Saved — leave blank to keep it' : 'Enter API secret' }}" autocomplete="new-password"></label></div><label><input type="checkbox" name="binance_enabled" value="1" @checked($settings['binance_enabled'] === '1')> Enable Binance integration</label><button class="btn secondary" type="submit" formaction="{{ route('admin.settings.binance-test') }}" formmethod="POST" style="margin-top:12px">Test Binance API</button></div>
<div class="card" style="margin-top:18px"><h2>Order Notifications</h2><p class="muted">When a payment/order is submitted, GigRanker can notify your Discord channel and Telegram admin/group.</p><div class="grid"><label>Discord webhook URL<input type="url" name="discord_order_webhook" placeholder="{{ $settings['discord_webhook_set'] ? 'Saved — leave blank to keep it' : 'https://discord.com/api/webhooks/...' }}"></label><label>Telegram chat ID<input name="telegram_order_chat_id" value="{{ old('telegram_order_chat_id',$settings['telegram_order_chat_id']) }}" placeholder="-1001234567890"></label><label style="grid-column:1/-1">Telegram bot token<input type="password" name="telegram_bot_token" placeholder="{{ $settings['telegram_token_set'] ? 'Saved — leave blank to keep it' : 'Bot token from BotFather' }}"></label></div></div>
<button class="btn" type="submit" style="margin-top:18px">Save Settings</button>
</form></div>
@endsection
