@extends('layouts.admin')
@section('content')
<div class="page-head"><div><div class="eyebrow">Configuration</div><h1>Admin Settings</h1><p>Manage AI providers and BEP20 USDT without editing server code.</p></div></div>
<form method="POST" action="{{ route('admin.settings.update') }}"><div class="grid">
<div class="panel span-8"><div class="panel-head"><h2>AI Provider</h2><span class="badge">Encrypted</span></div><div class="form-grid"><div><label>Primary provider</label><select name="ai_provider">@foreach(['gemini','groq','openai'] as $provider)<option value="{{ $provider }}" @selected($settings['ai_provider'] === $provider)>{{ ucfirst($provider) }}</option>@endforeach</select></div><div><label>Gemini model</label><input name="gemini_model" value="{{ $settings['gemini_model'] }}"></div><div><label>Groq model</label><input name="groq_model" value="{{ $settings['groq_model'] }}"></div><div><label>OpenAI model</label><input name="openai_model" value="{{ $settings['openai_model'] }}"></div></div></div>
<div class="panel span-4"><div class="panel-head"><h2>Provider status</h2></div><div style="display:grid;gap:10px"><span class="badge {{ $settings['gemini_key_set'] ? 'success' : 'danger' }}">Gemini: {{ $settings['gemini_key_set'] ? 'Configured' : 'Missing' }}</span><span class="badge {{ $settings['groq_key_set'] ? 'success' : 'danger' }}">Groq: {{ $settings['groq_key_set'] ? 'Configured' : 'Missing' }}</span><span class="badge {{ $settings['openai_key_set'] ? 'success' : 'danger' }}">OpenAI: {{ $settings['openai_key_set'] ? 'Configured' : 'Missing' }}</span></div></div>
<div class="panel span-12"><div class="panel-head"><h2>API Credentials</h2><span class="muted">Leave blank to keep the saved key</span></div><div class="form-grid"><div><label>Gemini API Key</label><input type="password" name="gemini_api_key" placeholder="{{ $settings['gemini_key_set'] ? 'Saved — leave blank to keep' : 'Enter API key' }}" autocomplete="new-password"></div><div><label>Groq API Key</label><input type="password" name="groq_api_key" placeholder="{{ $settings['groq_key_set'] ? 'Saved — leave blank to keep' : 'Enter API key' }}" autocomplete="new-password"></div><div><label>OpenAI API Key</label><input type="password" name="openai_api_key" placeholder="{{ $settings['openai_key_set'] ? 'Saved — leave blank to keep' : 'Enter API key' }}" autocomplete="new-password"></div></div></div>
<div class="panel span-12"><div class="panel-head"><h2>BEP20 USDT</h2><span class="badge success">BSC</span></div><div class="form-grid"><div><label>Receiving wallet address</label><input name="bep20_address" value="{{ $settings['bep20_address'] }}" required></div><div><label>Network</label><select name="bep20_network"><option value="BSC" selected>BNB Smart Chain (BEP20)</option></select></div></div><p class="muted" style="font-size:12px;margin-bottom:0">Only use a wallet you control. Verify the network and address before accepting live payments.</p></div>
<div class="span-12" style="display:flex;justify-content:flex-end"><button class="btn" type="submit">Save Settings</button></div>
</div>@csrf</form>
@endsection
